package frontend;
import javax.swing.table.DefaultTableModel;
import backend.Pessoa;
import backend.Agenda;
import backend.Endereco;
import backend.farmacia.PessoaJuridica;
import backend.usuario.PessoaFisica;

public class ContatosFarmacias extends javax.swing.JFrame {
    PessoaFisica pessoa;
    /**
     * Creates new form Contatosemergencia
     */
    public ContatosFarmacias() {
    }
    public void receber(PessoaFisica pessoa){
        this.pessoa = pessoa;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        voltar = new javax.swing.JButton();
        novaFarmacia = new javax.swing.JButton();
        excluirFarmacia = new javax.swing.JButton();
        nomeFarmacia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numeroFarmacia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enderecoFarmacia = new javax.swing.JTextField();
        salvarFarmacia = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFarmacia = new javax.swing.JTable();
        cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        voltar.setText("Retornar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        novaFarmacia.setText("Nova Farmacia");
        novaFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaFarmaciaActionPerformed(evt);
            }
        });

        excluirFarmacia.setText("Excluir");
        excluirFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFarmaciaActionPerformed(evt);
            }
        });

        nomeFarmacia.setEnabled(false);

        jLabel1.setText("Nome da farmacia:");

        jLabel2.setText("Numero do telefone:");

        numeroFarmacia.setEnabled(false);

        jLabel3.setText("endereço da farmacia:");

        enderecoFarmacia.setEnabled(false);

        salvarFarmacia.setText("salvar");
        salvarFarmacia.setEnabled(false);
        salvarFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarFarmaciaActionPerformed(evt);
            }
        });

        tabelaFarmacia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Numero ", "Endereço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaFarmacia);

        cancelar.setText("cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(novaFarmacia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(excluirFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 419, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(enderecoFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nomeFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salvarFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novaFarmacia)
                    .addComponent(excluirFarmacia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salvarFarmacia)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        DefaultTableModel val = (DefaultTableModel) tabelaFarmacia.getModel();
        for(Pessoa farmaciaCont : this.pessoa.getContatosFarmacias().getContatos()){
            String nome = farmaciaCont.getNome();
            String numero = farmaciaCont.getTelefone();
            String enderecoTa = ((Endereco) farmaciaCont.getParticularidade()).toStringFront();
            val.addRow(new String[]{nome, numero, enderecoTa});   
        }

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {                                       

        Home tela = new Home();
        tela.receber(pessoa);
        tela.setVisible(true);
        dispose();        // TODO add your handling code here:
    }                                      

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        ContatosFarmacias farmacia = new ContatosFarmacias();
        farmacia.receber(pessoa);
        farmacia.setVisible(true);
        dispose();
    }                                        

    private void novaFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {                                             
        nomeFarmacia.setEnabled(true);
        numeroFarmacia.setEnabled(true);
        enderecoFarmacia.setEnabled(true);
        salvarFarmacia.setEnabled(true);
        cancelar.setEnabled(true);
    }                                            

    private void salvarFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {                                               
        Agenda agendaTemp = this.pessoa.getContatosFarmacias();
        if(agendaTemp == null){
            agendaTemp = new Agenda();
        }
        Endereco endereco = new Endereco(enderecoFarmacia.getText(), "numero", "complemento");
        PessoaJuridica farmacia = new PessoaJuridica(nomeFarmacia.getText(), numeroFarmacia.getText(), "@gmail", "senhaLixo", "cnpj", endereco);
        farmacia.salvarDadosArquivo();
        this.pessoa.addFarmaciaAosContatos(farmacia);
        ContatosFarmacias contatoFarmacia = new ContatosFarmacias();
        contatoFarmacia.receber(pessoa);
        contatoFarmacia.setVisible(true);
        dispose();
    }                                              

    private void excluirFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String nomeFarmaciaExcluir = tabelaFarmacia.getValueAt(tabelaFarmacia.getSelectedRow(),0).toString();
        Agenda agendaTemp = this.pessoa.getContatosFarmacias();
        if(agendaTemp == null){
            return;
        }
        this.pessoa.removerContatoFarmacia(nomeFarmaciaExcluir);
        ContatosFarmacias contatoFarmacia = new ContatosFarmacias();
        contatoFarmacia.receber(pessoa);
        contatoFarmacia.setVisible(true);
        dispose();
    }   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContatosFarmacias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContatosFarmacias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContatosFarmacias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContatosFarmacias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContatosFarmacias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField enderecoFarmacia;
    private javax.swing.JButton excluirFarmacia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeFarmacia;
    private javax.swing.JButton novaFarmacia;
    private javax.swing.JTextField numeroFarmacia;
    private javax.swing.JButton salvarFarmacia;
    private javax.swing.JTable tabelaFarmacia;
    private javax.swing.JButton voltar;
    // End of variables declaration                   
}
