package frontend;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leosa
 */
public class ListaRemedios extends javax.swing.JFrame {
    String nomeDaPessoaH;
    String idadeDaPessoaH;
    String enderecoDaPessoaH;

    /**
     * Creates new form listaremedio
     */
    public ListaRemedios() {
    }
    public void receber(String _nome, String _idade,String _endereco){
        nomeDaPessoaH = _nome;
        idadeDaPessoaH = _idade;
        enderecoDaPessoaH = _endereco;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        voltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        horaRemedio = new javax.swing.JComboBox<>();
        nomeRemedio = new javax.swing.JTextField();
        quantidadeRemedio = new javax.swing.JTextField();
        segunda = new javax.swing.JCheckBox();
        terca = new javax.swing.JCheckBox();
        quarta = new javax.swing.JCheckBox();
        quinta = new javax.swing.JCheckBox();
        sexta = new javax.swing.JCheckBox();
        sabado = new javax.swing.JCheckBox();
        domingo = new javax.swing.JCheckBox();
        novoRemedio = new javax.swing.JButton();
        salvar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaRemedio = new javax.swing.JTable();
        intervaloRemedio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        voltar.setText("Retornar");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do remedio:");

        jLabel2.setText("Quantidade:");

        jLabel3.setText("Dias da semana:");

        jLabel4.setText("Hora inicial:");

        horaRemedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00hr", "01hr", "02hr", "03hr", "04hr", "05hr", "06hr", "07hr", "08hr", "09hr", "10hr", "11hr", "12hr", "13hr", "14hr", "15hr", "16hr", "17hr", "18hr", "19hr", "20hr", "21hr", "22hr", "23hr" }));
        horaRemedio.setEnabled(false);
        horaRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horaRemedioActionPerformed(evt);
            }
        });

        nomeRemedio.setEnabled(false);

        quantidadeRemedio.setEnabled(false);
        quantidadeRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantidadeRemedioActionPerformed(evt);
            }
        });

        segunda.setText("Segunda");
        segunda.setEnabled(false);
        segunda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundaActionPerformed(evt);
            }
        });

        terca.setText("Terça");
        terca.setEnabled(false);

        quarta.setText("Quarta");
        quarta.setEnabled(false);

        quinta.setText("Quinta");
        quinta.setEnabled(false);

        sexta.setText("Sexta");
        sexta.setEnabled(false);

        sabado.setText("Sabado");
        sabado.setEnabled(false);

        domingo.setText("Domingo");
        domingo.setEnabled(false);
        domingo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                domingoActionPerformed(evt);
            }
        });

        novoRemedio.setText("Novo Remedio");
        novoRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoRemedioActionPerformed(evt);
            }
        });

        salvar.setText("salvar");
        salvar.setEnabled(false);
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        cancelar.setText("cancelar");
        cancelar.setEnabled(false);
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        editar.setText("editar");

        excluir.setText("excluir");

        tabelaRemedio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Remedio", "Quantidade", "Dias da semana", "Hora"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaRemedio.setToolTipText("");
        jScrollPane2.setViewportView(tabelaRemedio);

        intervaloRemedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 vez por dia", "de 1 em 1 hora", "de 2 em 2 horas", "de 3 em 3 horas", "de 4 em 4 horas", "de 5 em 5 horas", "de 6 em 6 horas", "de 7 em 7 horas", "de 8 em 8 horas", "de 9 em 9 horas", "de 10 em 10 horas", "de 11 em 11 horas", "de 12 em 12 horas" }));
        intervaloRemedio.setEnabled(false);
        intervaloRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intervaloRemedioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(intervaloRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(horaRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(segunda)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(terca)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(quarta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(quinta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sexta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sabado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(domingo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(quantidadeRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(voltar)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 104, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
            .addGroup(layout.createSequentialGroup()
                .addComponent(novoRemedio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(voltar)
                .addGap(12, 12, 12)
                .addComponent(novoRemedio)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeRemedio, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(quantidadeRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(horaRemedio, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intervaloRemedio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(segunda)
                            .addComponent(terca)
                            .addComponent(quarta)
                            .addComponent(quinta)
                            .addComponent(sexta)
                            .addComponent(sabado)
                            .addComponent(domingo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluir)
                    .addComponent(editar))
                .addGap(24, 24, 24))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {                                       

    Home tela = new Home();
    tela.receber(nomeDaPessoaH, idadeDaPessoaH,enderecoDaPessoaH);
    tela.setVisible(true);
    dispose();        // TODO add your handling code here:
    }                                      

    private void novoRemedioActionPerformed(java.awt.event.ActionEvent evt) {                                            
        nomeRemedio.setEnabled(true);
        quantidadeRemedio.setEnabled(true);
        cancelar.setEnabled(true);
        segunda.setEnabled(true);
        terca.setEnabled(true);
        quarta.setEnabled(true);
        quinta.setEnabled(true);
        sexta.setEnabled(true);
        sabado.setEnabled(true);
        domingo.setEnabled(true);
        salvar.setEnabled(true);
        horaRemedio.setEnabled(true);
        
    }                                           

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {                                         
    ListaRemedios lista = new ListaRemedios();
    lista.receber(nomeDaPessoaH,idadeDaPessoaH,enderecoDaPessoaH);
    lista.setVisible(true);
    dispose();
    }                                        

    private void segundaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void quantidadeRemedioActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        // TODO add your handling code here:
    }                                                 

    private void domingoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {                                       
        String dias ="";
        int hora;
        String horaEmString;
        if (segunda.isSelected()){dias =  dias +"seg, ";}
        if (terca.isSelected()){dias =  dias +"ter, ";}
        if (quarta.isSelected()){dias =  dias +"qua, ";}
        if (quinta.isSelected()){dias =  dias +"qui, ";}
        if (sexta.isSelected()){dias =  dias +"sex, ";}
        if (sabado.isSelected()){dias =  dias +"sab, ";}
        if (domingo.isSelected()){dias =  dias +"dom, ";}

        if(horaRemedio.getSelectedItem().equals("00hr")){hora = 0; horaEmString="00hr";}
        if(horaRemedio.getSelectedItem().equals("01hr")){hora = 1; horaEmString="01hr";}
        if(horaRemedio.getSelectedItem().equals("02hr")){hora = 2; horaEmString="02hr";}
        if(horaRemedio.getSelectedItem().equals("03hr")){hora = 3; horaEmString="03hr";}
        if(horaRemedio.getSelectedItem().equals("04hr")){hora = 4; horaEmString="04hr";}
        if(horaRemedio.getSelectedItem().equals("05hr")){hora = 5; horaEmString="05hr";}
        if(horaRemedio.getSelectedItem().equals("06hr")){hora = 6; horaEmString="06hr";}
        if(horaRemedio.getSelectedItem().equals("07hr")){hora = 7; horaEmString="07hr";}
        if(horaRemedio.getSelectedItem().equals("08hr")){hora = 8; horaEmString="08hr";}
        if(horaRemedio.getSelectedItem().equals("09hr")){hora = 9; horaEmString="09hr";}
        if(horaRemedio.getSelectedItem().equals("10hr")){hora = 10; horaEmString="10hr";}
        if(horaRemedio.getSelectedItem().equals("11hr")){hora = 11; horaEmString="11hr";}
        if(horaRemedio.getSelectedItem().equals("12hr")){hora = 12; horaEmString="12hr";}
        if(horaRemedio.getSelectedItem().equals("13hr")){hora = 13; horaEmString="13hr";}
        if(horaRemedio.getSelectedItem().equals("14hr")){hora = 14; horaEmString="14hr";}
        if(horaRemedio.getSelectedItem().equals("15hr")){hora = 15; horaEmString="15hr";}
        if(horaRemedio.getSelectedItem().equals("16hr")){hora = 16; horaEmString="16hr";}
        if(horaRemedio.getSelectedItem().equals("17hr")){hora = 17; horaEmString="17hr";}
        if(horaRemedio.getSelectedItem().equals("18hr")){hora = 18; horaEmString="18hr";}
        if(horaRemedio.getSelectedItem().equals("19hr")){hora = 19; horaEmString="19hr";}
        if(horaRemedio.getSelectedItem().equals("20hr")){hora = 20; horaEmString="20hr";}
        if(horaRemedio.getSelectedItem().equals("21hr")){hora = 21; horaEmString="21hr";}
        if(horaRemedio.getSelectedItem().equals("22hr")){hora = 22; horaEmString="22hr";}
        if(horaRemedio.getSelectedItem().equals("23hr")){hora = 23; horaEmString="23hr";}
    }                                      

    private void horaRemedioActionPerformed(java.awt.event.ActionEvent evt) {                                            
    intervaloRemedio.setEnabled(true);        // TODO add your handling code here:
    }                                           

    private void intervaloRemedioActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaRemedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaRemedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaRemedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaRemedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaRemedios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton cancelar;
    private javax.swing.JCheckBox domingo;
    private javax.swing.JButton editar;
    private javax.swing.JButton excluir;
    private javax.swing.JComboBox<String> horaRemedio;
    private javax.swing.JComboBox<String> intervaloRemedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeRemedio;
    private javax.swing.JButton novoRemedio;
    private javax.swing.JTextField quantidadeRemedio;
    private javax.swing.JCheckBox quarta;
    private javax.swing.JCheckBox quinta;
    private javax.swing.JCheckBox sabado;
    private javax.swing.JButton salvar;
    private javax.swing.JCheckBox segunda;
    private javax.swing.JCheckBox sexta;
    private javax.swing.JTable tabelaRemedio;
    private javax.swing.JCheckBox terca;
    private javax.swing.JButton voltar;
    // End of variables declaration                   
}
