package frontend;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import backend.Endereco;
import backend.farmacia.PessoaJuridica;
import inicio.MedAlerta;
public class LoginFarmacia extends javax.swing.JFrame {

    /**
     * Creates new form LoguinFarmacia
     */
    public LoginFarmacia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomeFarmacia = new javax.swing.JLabel();
        nomeFarmaciaEntrada = new javax.swing.JTextField();
        cnpjFarmacia = new javax.swing.JLabel();
        cnpjFarmaciaEntrada = new javax.swing.JTextField();
        proximoFarmacia = new javax.swing.JButton();
        emailLF = new javax.swing.JLabel();
        senhaLF = new javax.swing.JLabel();
        senhaLFE = new javax.swing.JPasswordField();
        emailLFE = new javax.swing.JTextField();
        telefoneFarmacia = new javax.swing.JLabel();
        numeroDaFarmaciaEntrada = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        complemento = new javax.swing.JLabel();
        numero = new javax.swing.JLabel();
        rua = new javax.swing.JLabel();
        ruaLF = new javax.swing.JTextField();
        numeroL = new javax.swing.JTextField();
        complementoLF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Farmacia"));

        nomeFarmacia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nomeFarmacia.setText("Nome da farmácia:");
        nomeFarmacia.setToolTipText("");

        nomeFarmaciaEntrada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nomeFarmaciaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeFarmaciaEntradaActionPerformed(evt);
            }
        });

        cnpjFarmacia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cnpjFarmacia.setText("CNPJ:");
        cnpjFarmacia.setToolTipText("");

        cnpjFarmaciaEntrada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cnpjFarmaciaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnpjFarmaciaEntradaActionPerformed(evt);
            }
        });

        proximoFarmacia.setText("Prox.");
        proximoFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoFarmaciaActionPerformed(evt);
            }
        });

        emailLF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailLF.setText("Email:");
        emailLF.setToolTipText("");

        senhaLF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        senhaLF.setText("Senha");
        senhaLF.setToolTipText("");

        senhaLFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaLFEActionPerformed(evt);
            }
        });

        emailLFE.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLFE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailLFEActionPerformed(evt);
            }
        });

        telefoneFarmacia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        telefoneFarmacia.setText("Telefone:");
        telefoneFarmacia.setToolTipText("");

        numeroDaFarmaciaEntrada.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numeroDaFarmaciaEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroDaFarmaciaEntradaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        complemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        complemento.setText("Complemento:");
        complemento.setToolTipText("");

        numero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numero.setText("Número:");
        numero.setToolTipText("");

        rua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rua.setText("Nome da rua:");
        rua.setToolTipText("");

        ruaLF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ruaLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruaLFActionPerformed(evt);
            }
        });

        numeroL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numeroL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroLActionPerformed(evt);
            }
        });

        complementoLF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        complementoLF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complementoLFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(complemento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(complementoLF)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rua)
                            .addComponent(numero))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroL, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ruaLF, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rua)
                    .addComponent(ruaLF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numero)
                    .addComponent(numeroL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complemento)
                    .addComponent(complementoLF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(emailLF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(senhaLF))
                                .addGap(86, 86, 86)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(senhaLFE, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailLFE, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cnpjFarmacia))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cnpjFarmaciaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nomeFarmaciaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numeroDaFarmaciaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(84, 209, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(telefoneFarmacia)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(117, 117, 117)
                .addComponent(proximoFarmacia)
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLF)
                    .addComponent(emailLFE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaLF)
                    .addComponent(senhaLFE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeFarmacia)
                    .addComponent(nomeFarmaciaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnpjFarmacia)
                    .addComponent(cnpjFarmaciaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneFarmacia)
                    .addComponent(numeroDaFarmaciaEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(proximoFarmacia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void nomeFarmaciaEntradaActionPerformed(java.awt.event.ActionEvent evt) {                                                    

    }                                                   

    private void cnpjFarmaciaEntradaActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void proximoFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {                                                
        String telefone = numeroDaFarmaciaEntrada.getText();
        String nomenFarmacia = nomeFarmaciaEntrada.getText();
        String cnpjFarmacia = cnpjFarmaciaEntrada.getText();
        String email = emailLFE.getText();
        String senha = String.copyValueOf(senhaLFE.getPassword());
        String nomeRua = ruaLF.getText();
        String numeroRua = numeroL.getText();
        String complementoRua = complementoLF.getText();
        Endereco endereco = new Endereco(nomeRua, numeroRua, complementoRua);
        if(senha == ""||emailLF.getText().trim().isEmpty()||nomeFarmaciaEntrada.getText().trim().isEmpty()|| cnpjFarmaciaEntrada.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"Precisa preencher todas as opções corretamente!");
            LoginFarmacia login = new LoginFarmacia();
            login.setVisible(true);
            dispose();
        }
        else{
            PessoaJuridica farmacia = new PessoaJuridica(nomenFarmacia,telefone,email,senha,cnpjFarmacia, endereco);
            farmacia.salvarDadosArquivo();
            MedAlerta.setFimDaEspera(false);
            HomeDaFarmacia tela = new HomeDaFarmacia();
            tela.receber(farmacia);
            tela.setVisible(true);
            dispose();
        }
    }                                               

    private void senhaLFEActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void emailLFEActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void numeroDaFarmaciaEntradaActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void ruaLFActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void numeroLActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void complementoLFActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFarmacia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFarmacia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel cnpjFarmacia;
    private javax.swing.JTextField cnpjFarmaciaEntrada;
    private javax.swing.JLabel complemento;
    private javax.swing.JTextField complementoLF;
    private javax.swing.JLabel emailLF;
    public javax.swing.JTextField emailLFE;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nomeFarmacia;
    public javax.swing.JTextField nomeFarmaciaEntrada;
    private javax.swing.JLabel numero;
    private javax.swing.JTextField numeroDaFarmaciaEntrada;
    private javax.swing.JTextField numeroL;
    private javax.swing.JButton proximoFarmacia;
    private javax.swing.JLabel rua;
    public javax.swing.JTextField ruaLF;
    private javax.swing.JLabel senhaLF;
    private javax.swing.JPasswordField senhaLFE;
    private javax.swing.JLabel telefoneFarmacia;
    // End of variables declaration                   
}