package frontend;

import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author leosa
 */
public class LoginPessoa extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LoginPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        naoMexerNisso = new javax.swing.JPanel();
        nome_l = new javax.swing.JLabel();
        nome_l_e = new javax.swing.JTextField();
        idade_l = new javax.swing.JLabel();
        idade_l_e = new javax.swing.JTextField();
        endereco_l = new javax.swing.JLabel();
        endereco_l_e = new javax.swing.JTextField();
        prox_l = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        naoMexerNisso.setBorder(javax.swing.BorderFactory.createTitledBorder("Login Pessoa"));

        nome_l.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nome_l.setText("Nome competo:");
        nome_l.setToolTipText("");

        nome_l_e.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nome_l_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_l_eActionPerformed(evt);
            }
        });

        idade_l.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        idade_l.setText("Idade:");
        idade_l.setToolTipText("");

        idade_l_e.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idade_l_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idade_l_eActionPerformed(evt);
            }
        });

        endereco_l.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endereco_l.setText("Endereço:");
        endereco_l.setToolTipText("");

        endereco_l_e.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        endereco_l_e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endereco_l_eActionPerformed(evt);
            }
        });

        prox_l.setText("Prox.");
        prox_l.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prox_lActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout naoMexerNissoLayout = new javax.swing.GroupLayout(naoMexerNisso);
        naoMexerNisso.setLayout(naoMexerNissoLayout);
        naoMexerNissoLayout.setHorizontalGroup(
            naoMexerNissoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naoMexerNissoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(naoMexerNissoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idade_l)
                    .addComponent(nome_l)
                    .addComponent(endereco_l))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(naoMexerNissoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(naoMexerNissoLayout.createSequentialGroup()
                        .addGroup(naoMexerNissoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_l_e, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endereco_l_e, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(162, Short.MAX_VALUE))
                    .addGroup(naoMexerNissoLayout.createSequentialGroup()
                        .addComponent(idade_l_e, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(prox_l)
                        .addGap(40, 40, 40))))
        );
        naoMexerNissoLayout.setVerticalGroup(
            naoMexerNissoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(naoMexerNissoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(naoMexerNissoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome_l, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome_l_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(naoMexerNissoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idade_l, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idade_l_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prox_l, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(naoMexerNissoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endereco_l, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endereco_l_e, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(naoMexerNisso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(naoMexerNisso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(639, 337));
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void nome_l_eActionPerformed(java.awt.event.ActionEvent evt) {                                         

    }                                        

    private void idade_l_eActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void endereco_l_eActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void prox_lActionPerformed(java.awt.event.ActionEvent evt) {                                       
    String nomenCompletoLogin = nome_l_e.getText();
    String idadeLogin = idade_l_e.getText();
    String enderecoLogin =  endereco_l_e.getText();
    if(idade_l_e.getText().trim().isEmpty()|| nome_l_e.getText().trim().isEmpty()|| endereco_l_e.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null,"Precisa preencher todas as opções corretamente!");
        LoginPessoa login = new LoginPessoa();
        login.setVisible(true);
        dispose();
    }
    else{
        Home tela = new Home();
        tela.receber(nomenCompletoLogin, idadeLogin,enderecoLogin);
        tela.setVisible(true);
        dispose();}
    

    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel endereco_l;
    private javax.swing.JTextField endereco_l_e;
    private javax.swing.JLabel idade_l;
    private javax.swing.JTextField idade_l_e;
    private javax.swing.JPanel naoMexerNisso;
    private javax.swing.JLabel nome_l;
    public javax.swing.JTextField nome_l_e;
    private javax.swing.JButton prox_l;
    // End of variables declaration                   
}
